### PR TITLE
Update zh_tw.json

### PR DESCRIPTION
**Pull request by dirtTW**
Update Translation
更新翻譯

### CODE REVIEW

**Comment by sakurawald** [comment]
sorry, i just don't see the pull-request, and push something new to the branch.
Can you pull the latest change from 'dev' branch, and merge it, re-push the work you did ?

**Comment by dirtTW** [comment]
> sorry, i just don't see the pull-request, and push something new to the branch. Can you pull the latest change from 'dev' branch, and merge it, re-push the work you did ?

Ah, I forgot to sync the fork. Wait for me

**Comment by sakurawald** [comment]
i move the '/lang' directory from '/assets/fuji/lang' into '/io/github/sakurawald/lang', for the compatibility with some other mod loader.

**Comment by dirtTW** [comment]
> /io/github/sakurawald/lan

oh okay, i will make another PR now

**Pull request closed without merging**
